export const movies = [
  {
    adult: false,
    backdrop_path: "/fOy2Jurz9k6RnJnMUMRDAgBwru2.jpg",
    genre_ids: [16, 10751, 35, 14],
    id: 508947,
    original_language: "en",
    original_title: "Turning Red",
    overview:
      "Thirteen-year-old Mei is experiencing the awkwardness of being a teenager with a twist – when she gets too excited, she transforms into a giant red panda.",
    popularity: 9926.676,
    poster_path: "/qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg",
    release_date: "2022-03-01",
    title: "Turning Red",
    video: false,
    vote_average: 7.5,
    vote_count: 1122,
  },
  {
    adult: false,
    backdrop_path: "/ewUqXnwiRLhgmGhuksOdLgh49Ch.jpg",
    genre_ids: [28, 12, 35, 878, 18],
    id: 696806,
    original_language: "en",
    original_title: "The Adam Project",
    overview:
      "After accidentally crash-landing in 2022, time-traveling fighter pilot Adam Reed teams up with his 12-year-old self on a mission to save the future.",
    popularity: 4751.084,
    poster_path: "/wFjboE0aFZNbVOF05fzrka9Fqyx.jpg",
    release_date: "2022-03-11",
    title: "The Adam Project",
    video: false,
    vote_average: 7,
    vote_count: 1270,
  },
];
